export const LEADERSHIP_ROLES: string[] = ['supervisor', 'coordenador', 'gestor', 'diretor', 'engenheiro', 'responsavel', 'gerente'];

// E-mail que receberá notificações de novas solicitações e uso diário
export const ADMIN_EMAIL_RECIPIENTS: string[] = ['deny.goncalves@risel.com.br', 'lorena.padilha@risel.com.br'];

// INSTRUÇÃO IMPORTANTE:
// O UID do usuário com o e-mail 'deny.goncalves@risel.com.br' DEVE ser inserido aqui.
export const DASHBOARD_OWNER_UID: string = 'PNeVyR2dDlXxPT2JSbk9GsPAqos2';

// Configurações do EmailJS
export const EMAILJS_SERVICE_ID = "service_k59tsfo";
export const EMAILJS_TEMPLATE_ID = "template_cjkcpr6";
export const EMAILJS_PUBLIC_KEY = "cuqP-0hxxKwPdRE5g";

export const SP_CITIES: string[] = Array.from(new Set([
  "Adamantina", "Aguai", "Agudos", "Águas Da Prata", "Águas de Lindoia", "Águas de Santa Barbara", 
  "Águas de São Pedro", "Alambari", "Alfredo Marcondes", "Altair", "Altinópolis", "Alto Alegre", 
  "Alumínio", "Álvares Florence", "Álvares Machado", "Álvaro de Carvalho", "Alvinlândia", 
  "Americana", "Américo Brasiliense", "Américo de Campos", "Amparo", "Analândia", "Andradina", 
  "Angatuba", "Anhembi", "Anhumas", "Aparecida", "Aparecida d'Oeste", "Apiaí", "Araçariguama", 
  "Araçatuba", "Araçoiaba Da Serra", "Aramina", "Arandu", "Arapuá", "Araraquara", "Araras", 
  "Arco-Íris", "Arealva", "Areias", "Areiópolis", "Ariranha", "Artur Nogueira", "Arujá", 
  "Aspásia", "Assis", "Atibaia", "Auriflama", "Avaí", "Avanhandava", "Avaré", "Bady Bassitt", 
  "Balbinos", "Bálsamo", "Bananal", "Barão de Antonina", "Barbosa", "Bariri", "Barra Bonita", 
  "Barra do Chapéu", "Barra do Turvo", "Barretos", "Barrinha", "Barueri", "Bastos", "Batatais", 
  "Bauru", "Bebedouro", "Bento de Abreu", "Bernardino de Campos", "Bertioga", "Bilac", "Birigui", 
  "Biritiba-Mirim", "Boa Esperança do Sul", "Bocaina", "Bofete", "Boituva", "Bom Jesus Dos Perdões", 
  "Bom Sucesso de Itararé", "Borá", "Boraceia", "Borborema", "Borebi", "Botucatu", "Bragança Paulista", 
  "Braúna", "Brejo Alegre", "Brodowski", "Brotas", "Buri", "Buritama", "Buritizal", "Cabrália Paulista", 
  "Cabreúva", "Caçapava", "Cachoeira Paulista", "Caconde", "Cafelândia", "Caiabu", "Caieiras", 
  "Caiuá", "Cajamar", "Cajati", "Cajobi", "Cajuru", "Campina do Monte Alegre", "Campinas", 
  "Campo Limpo Paulista", "Campos do Jordão", "Campos Novos Paulista", "Cananéia", "Canas", 
  "Cândido Mota", "Cândido Rodrigues", "Canitar", "Capão Bonito", "Capela do Alto", "Capivari", 
  "Caraguatatuba", "Carapicuíba", "Cardoso", "Casa Branca", "Cássia Dos Coqueiros", "Castilho", 
  "Catanduva", "Catiguá", "Cedral", "Cerqueira César", "Cerquilho", "Cesário Lange", "Charqueada", 
  "Chavantes", "Clementina", "Colina", "Colômbia", "Conchal", "Conchas", "Cordeirópolis", 
  "Coroados", "Coronel Macedo", "Corumbataí", "Cosmópolis", "Cosmorama", "Cotia", "Cravinhos", 
  "Cristais Paulista", "Cruzália", "Cruzeiro", "Cubatão", "Cunha", "Descalvado", "Diadema", 
  "Dirce Reis", "Divinolândia", "Dobrada", "Dois Córregos", "Dolcinópolis", "Dourado", "Dracena", 
  "Duartina", "Dumont", "Echaporã", "Eldorado", "Elias Fausto", "Elisiário", "Embaúba", 
  "Embu Das Artes", "Embu-Guaçu", "Emilianópolis", "Engenheiro Coelho", "Espírito Santo do Pinhal", 
  "Espírito Santo do Turvo", "Estiva Gerbi", "Estrela d'Oeste", "Estrela do Norte", 
  "Euclides Da Cunha Paulista", "Fartura do Piauí", "Fernandópolis", "Fernando Prestes", "Fernão", 
  "Ferraz de Vasconcelos", "Flora Rica", "Floreal", "Flórida Paulista", "Florínea", "Franca", 
  "Francisco Morato", "Franco Da Rocha", "Gabriel Monteiro", "Gália", "Garça", "Gastão Vidigal", 
  "Gavião Peixoto", "General Salgado", "Getulina", "Glicério", "Guaiçara", "Guaimbê", 
  "Guapiara", "Guará", "Guaraçaí", "Guaraci", "Guarani d'Oeste", "Guarantã", 
  "Guararapes", "Guararema", "Guaratinguetá", "Guareí", "Guariba", "Guarujá", "Guarulhos", 
  "Guatapará", "Guzolândia", "Herculândia", "Holambra", "Hortolândia", "Iacanga", "Iacri", 
  "Iaras", "Ibaté", "Ibirá", "Ibirarema", "Ibitinga", "Ibiúna", "Icem", "Iepê", "Igarçu do Tietê", 
  "Igarapava", "Igaratá", "Iguape", "Ilha Comprida", "Ilha Solteira", "Ilhabela", "Indaiatuba", 
  "Indiana", "Indiaporã", "Inúbia Paulista", "Ipaussu", "Iperó", "Ipeúna", "Ipiguá", "Iporanga", 
  "Ipuã", "Iracemápolis", "Irapuã", "Irapuru", "Itaberá", "Itaí", "Itajobi", "Itaju", "Itanhaém", 
  "Itaoca", "Itapecerica Da Serra", "Itapetininga", "Itapeva", "Itapevi", "Itapira", 
  "Itapirapuã Paulista", "Itápolis", "Itaporanga", "Itapuí", "Itapura", "Itaquaquecetuba", 
  "Itararé", "Itariri", "Itatiba", "Itatinga", "Itirapina", "Itirapuã", "Itobi", "Itu", "Itupeva", 
  "Ituverava", "Jaborandi", "Jaboticabal", "Jacareí", "Jaci", "Jacupiranga", "Jaguariúna", 
  "Jales", "Jambeiro", "Jandira", "Jardinópolis", "Jarinu", "Jaú", "Jeriquara", "Joanópolis", 
  "João Ramalho", "José Bonifácio", "Júlio Mesquita", "Jumirim", "Jundiaí", "Junqueirópolis", 
  "Juquiá", "Juquitiba", "Lagoinha", "Laranjal Paulista", "Lavínia", "Lavrinhas", "Leme", 
  "Lençóis Paulista", "Limeira", "Lindoia", "Lins", "Lorena", "Lourdes", "Louveira", "Lucélia", 
  "Lucianópolis", "Luís Antônio", "Luiziânia", "Lupércio", "Lutécia", "Macatuba", "Macaubal", 
  "Macedônia", "Magda", "Mairinque", "Mairiporã", "Manduri", "Marabá Paulista", "Maracaí", 
  "Marapoama", "Mariápolis", "Marília", "Marinópolis", "Martinópolis", "Matão", "Mauá", 
  "Mendonça", "Meridiano", "Mesópolis", "Miguelópolis", "Mineiros do Tietê", "Mira Estrela", 
  "Miracatu", "Mirandópolis", "Mirante do Paranapanema", "Mirassol", "Mirassolândia", "Mococa", 
  "Mogi Das Cruzes", "Mogi Guaçu", "Mogi Mirim", "Mombuca", "Monções", "Mongaguá", 
  "Monte Alegre do Sul", "Monte Alto", "Monte Aprazível", "Monte Azul Paulista", "Monte Castelo", 
  "Monte Mor", "Monteiro Lobato", "Morro Agudo", "Morungaba", "Motuca", "Murutinga do Sul", 
  "Nantes", "Narandiba", "Natividade Da Serra", "Nazaré Paulista", "Neves Paulista", "Nhandeara", 
  "Nipoã", "Nova Aliança", "Nova Campina", "Nova Canaã Paulista", "Nova Castilho", "Nova Europa", 
  "Nova Granada", "Nova Guataporanga", "Nova Independência", "Nova Luzitânia", "Nova Odessa", 
  "Novais", "Novo Horizonte", "Nuporanga", "Ocauçu", "Óleo", "Olímpia", "Onda Verde", 
  "Oriente", "Orindiúva", "Orlândia", "Osasco", "Oscar Bressane", "Osvaldo Cruz", "Ourinhos", 
  "Ouro Verde", "Ouroeste", "Pacaembu", "Palestina", "Palmares Paulista", "Palmeira d'Oeste", 
  "Palmital", "Panorama", "Paraguaçu Paulista", "Paraibuna", "Paraíso", "Paranapanema", 
  "Paranapuã", "Parapuã", "Pardinho", "Pariquera-Açu", "Parisi", "Patrocínio Paulista", 
  "Pauliceia", "Paulínia", "Paulistânia", "Paulo de Faria", "Pederneiras", "Pedra Bela", 
  "Pedranópolis", "Pedregulho", "Pedreira", "Pedrinhas Paulista", "Pedro de Toledo", "Penápolis", 
  "Pereira Barreto", "Pereiras", "Peruíbe", "Piacatu", "Piedade", "Pilar do Sul", "Pindamonhangaba", 
  "Pindorama", "Pinhalzinho", "Piquerobi", "Piquete", "Piracaia", "Piracicaba", "Piraju", 
  "Pirajuí", "Pirangi", "Pirapora do Bom Jesus", "Pirapozinho", "Pirassununga", "Piratininga", 
  "Pitangueiras", "Planalto", "Platina", "Poá", "Poloni", "Pompéia", "Pongaí", "Pontal", 
  "Pontalinda", "Pontes Gestal", "Populina", "Porangaba", "Porto Feliz", "Porto Ferreira", "Potim", 
  "Potirendaba", "Pracinha", "Pradópolis", "Praia Grande", "Pratânia", "Presidente Alves", 
  "Presidente Bernardes", "Presidente Epitácio", "Presidente Prudente", "Presidente Venceslau", 
  "Promissão", "Quadra", "Quatá", "Queiroz", "Queluz", "Quintana", "Rafard", "Rancharia", 
  "Redenção Da Serra", "Regente Feijó", "Reginópolis", "Registro", "Restinga", "Ribeira", 
  "Ribeirão Bonito", "Ribeirão Branco", "Ribeirão Corrente", "Ribeirão do Sul", 
  "Ribeirão Dos Índios", "Ribeirão Grande", "Ribeirão Pires", "Ribeirão Preto", "Rifaina", 
  "Rincão", "Rinópolis", "Rio Claro", "Rio Das Pedras", "Rio Grande Da Serra", "Riolândia", 
  "Riverazul", "Rosana", "Roseira", "Rubiácea", "Rubinéia", "Sagres", "Sales", "Sales Oliveira", 
  "Salesópolis", "Salmourão", "Saltinho", "Salto de Pirapora", "Salto Grande", "Sandovalina", 
  "Santa Adélia", "Santa Albertina", "Santa Bárbara d'Oeste", "Santa Branca", "Santa Clara d'Oeste", 
  "Santa Cruz Da Conceição", "Santa Cruz Da Esperança", "Santa Cruz Das Palmeiras", 
  "Santa Cruz do Rio Pardo", "Santa Ernestina", "Santa Fé do Sul", "Santa Gertrudes", "Santa Isabel", 
  "Santa Lúcia", "Santa Maria Da Serra", "Santa Mercedes", "Santa Rita d'Oeste", 
  "Santa Rita do Passa Quatro", "Santa Rosa de Viterbo", "Santa Salete", "Santana Da Ponte Pensa", 
  "Santana de Parnaíba", "Santo Anastácio", "Santo André", "Santo Antônio Da Alegria", 
  "Santo Antônio de Posse", "Santo Antônio do Aracanguá", "Santo Antônio do Jardim", 
  "Santo Antônio do Pinhal", "Santo Expedito", "Santópolis do Aguapeí", "Santos", 
  "São Bento do Sapucaí", "São Bernardo do Campo", "São Caetano do Sul", "São Carlos", 
  "São Francisco", "São João Da Boa Vista", "São João Das Duas Pontes", "São João de Iracema", 
  "São João do Pau d'Alho", "São Joaquim Da Barra", "São José Da Bela Vista", 
  "São José do Barreiro", "São José do Rio Pardo", "São José do Rio Preto", "São José Dos Campos", 
  "São Lourenço Da Serra", "São Luiz do Paraitinga", "São Manuel", "São Miguel Arcanjo", 
  "São Paulo", "São Pedro do Turvo", "São Roque", "São Sebastião Da Grama", "São Simão", 
  "São Vicente", "Sarapuí", "Sarutaiá", "Sebastianópolis do Sul", "Serra Azul", "Serra Negra", 
  "Serrana", "Sertãozinho", "Sete Barras", "Severínia", "Silveiras", "Socorro", "Sorocaba", 
  "Sud Mennucci", "Sumaré", "Suzanápolis", "Suzano", "Tabapuã", "Tabatinga", "Taboão Da Serra", 
  "Taciba", "Taguaí", "Taiaçu", "Taiúva", "Tambaú", "Tanabi", "Tapiraí", "Tapiratiba", "Taquaral", 
  "Taquaritinga", "Taquarituba", "Taquarivaí", "Tarabai", "Tarumã", "Tatuí", "Taubaté", "Tejupá", 
  "Teodoro Sampaio", "Terra Roxa", "Tietê", "Timburi", "Torre de Pedra", "Torrinha", "Trabiju", 
  "Tremembé", "Três Fronteiras", "Tuiuti", "Tupã", "Tupi Paulista", "Turiúba", "Turmalina", 
  "Ubarana", "Ubatuba", "Ubirajara", "Uchoa", "União Paulista", "Urânia", "Uru", "Urupês", 
  "Valentim Gentil", "Valinhos", "Valparaíso", "Vargem", "Vargem Grande do Sul", 
  "Vargem Grande Paulista", "Várzea Paulista", "Vera Cruz", "Vinhedo", "Viradouro", 
  "Vista Alegre do Alto", "Vitória Brasil", "Votorantim", "Votuporanga", "Zacarias"
])).sort();

export const ALLOWED_PLATES: string[] = [
  "SYL0A67", "SYL0A68", "SYL0A69", "SYL0A66", "SHM5H54", "SHN2I61", "RNT6J71", "SIL3B70", "RTS2B13", "SIU1J48",
  "RTS2A88", "OPP9E18", "OPP9D76", "SUF8D94", "TZA6C24", "TZA6C22", "TZA6C30", "TZA6J06", "TZA6C31", "TZA6C36",
  "TZA6J41", "TZA6J29", "TZA6C27", "TZA6J35", "TZA6C21", "TZA6J27", "TZA6C37", "TZA6J53", "TZA6J57", "TZA6J23",
  "TZA6J37", "TZA6C20", "TZA6C14", "TZA6J55", "TZA6I64", "TZA6C44", "TZA6C25", "TZA6J28", "TZA6J58", "TZA6J33",
  "TZA6C43", "TZA6C39", "TZA6C18", "TZA6C33", "TZA6J16", "TZA6J32", "TZA6C29", "TZA6J31", "TZA6J25", "TZA6C40",
  "TZA6J26", "TZA6C26", "TZA6C38", "TZA6J30", "TYA5A63", "TYA5A66", "TYA5A73", "TYK2B50", "TYK2B94", "SJF2A28",
  "SJF2A58", "SJF2A93", "SJF2B23", "SJF2B57", "SJF2B63", "TEA9H58", "TXQ1D35", "TXN9A40", "TXN9A42", "TYP6J30",
  "SHT8C33"
];
